server:
  servlet:
    context-path: /testA
  port: 8091
spring:
  application:
    name: s1
  datasource:
    url:  jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    #password: 1234
    password: 1111a!
    #name: master1
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/regist/eureka/